"""add missing columns to candidate table

Revision ID: 8fa638ac9ae7
Revises: c9f93034cc69
Create Date: 2025-09-20 13:44:31.502466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa638ac9ae7'
down_revision = 'c9f93034cc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing columns to the existing candidate table
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))  # Make nullable first
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('processed_data', sa.JSON(), nullable=True))
        
        # Create foreign key constraint
        batch_op.create_foreign_key('fk_candidate_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_constraint('fk_candidate_user_id', type_='foreignkey')
        batch_op.drop_column('processed_data')
        batch_op.drop_column('score')
        batch_op.drop_column('status')
        batch_op.drop_column('file_path')
        batch_op.drop_column('filename')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('user_id')
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###
